version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "8004:8000"
    volumes:
      - ./app:/usr/src/app
    environment:
      - TZ=America/Mexico_City
      - PYTHONUNBUFFERED=1
      - PREFIX
      - PROD
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - CLOUDINARY_URL
      - NEO4J_URI
      - NEO4J_USER
      - NEO4J_PASS
    restart: unless-stopped